- name: Update apt repository cache
  apt:
    update_cache: yes

- name: Install basic dependencies
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - acl
      - git
    state: present